AWSTemplateFormatVersion: 2010-09-09
Description: Upload APP - Demo C1 - FSS
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: '[ Customizable section ]'
      Parameters:
      - S3BucketToScan
      - ExternalID
      - TriggerWithObjectCreatedEvent
    ParameterLabels:
      S3BucketToScan:
        default: S3BucketToScan
      ExternalID:
        default: ExternalID
      TriggerWithObjectCreatedEvent:
        default: "true"
Parameters:
  S3BucketToScan:
    AllowedPattern: ^[0-9a-z]+([0-9a-z-]*[0-9a-z])*$
    ConstraintDescription: S3 bucket name can include numbers, lowercase letters,
      and hyphens (-). It cannot start or end with a hyphen (-).
    Description: The S3 bucket to scan. Specify an the name of S3 Scan.
    Default: test
    Type: String
  ExternalID:
    Description: The External ID, You can get the External ID from the ScannerStack
      Parameters or by API https://cloudone.trendmicro.com/docs/file-storage-security/api-reference/#tag/External-ID
    Default: '123456789012'
    Type: String
  TriggerWithObjectCreatedEvent:
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: If the s3:ObjectCreated:* event of the S3BucketToScan is in use, set this option to false. Then trigger the scans by invoking the deployed BucketListenerLambda.
    Type: String
  AWSRegion:
    Description: AWS Region
    Default: us-east-1
    Type: String
Resources:
  tmapi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
        - GET
        - POST
        - DELETE
        - OPTIONS
        AllowHeaders:
        - '*'
        AllowOrigins:
        - '*'
  CheckResultScan:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/resultScan.js
      Handler: resultScan.handler
      Runtime: nodejs12.x
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          UploadBucket:
            Ref: S3UploadBucket
      Policies:
      - S3FullAccessPolicy:
          BucketName:
            Ref: S3UploadBucket
      Events:
        UploadAssetAPI:
          Type: HttpApi
          Properties:
            Path: /status
            Method: post
            ApiId:
              Ref: tmapi
  UploadRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/uploader.js
      Handler: uploader.handler
      Runtime: nodejs12.x
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          UploadBucket:
            Ref: S3UploadBucket
      Policies:
      - S3WritePolicy:
          BucketName:
            Ref: S3UploadBucket
      - LambdaInvokePolicy:
          FunctionName:
            Ref: CheckResultScan
      Events:
        UploadAssetAPI:
          Type: HttpApi
          Properties:
            Path: /uploads
            Method: get
            ApiId:
              Ref: tmapi
  S3UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - HEAD
          AllowedOrigins:
          - '*'
  AllInOneFSS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: Templates/FSS-All-In-One.template
      Parameters:
        ExternalID:
          Ref: ExternalID
        S3BucketToScan:
          Ref: S3UploadBucket
        TriggerWithObjectCreatedEvent:
          Ref: TriggerWithObjectCreatedEvent
Outputs:
  APIendpoint:
    Description: HTTP API endpoint URL
    Value:
      Fn::Sub: https://${tmapi}.execute-api.${AWS::Region}.amazonaws.com
  S3UploadBucketName:
    Description: Upload Application for Demo C1 - FSS
    Value:
      Ref: S3UploadBucket
  StorageStackManagementRoleARN:
    Description: The ARN of the IAM role for File Storage Security backend services
      to manage the deployed resources.
    Value:
      Fn::GetAtt:
      - StorageStackFSS
      - Outputs.StorageStackManagementRoleARN
