version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "upload-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fzz49c7ezobx"
s3_prefix = "upload-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
