AWSTemplateFormatVersion: 2010-09-09
Description: Upload APP - Demo C1 - FSS
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: '[ Customizable section ]'
      Parameters:
      - S3BucketToScan
      - S3QuarantineBucketDemoApp
      - ScannerAWSAccount
      - ExternalID
      - ScannerSQSURL
      - PromoteMode
      - QuarantineMode
    ParameterLabels:
      S3BucketToScan:
        default: S3BucketToScan
      S3QuarantineBucketDemoApp:
        default: S3QuarantineBucketDemoApp
      ScannerAWSAccount:
        default: ScannerAWSAccount
      ExternalID:
        default: ExternalID
      ScannerSQSURL:
        default: ScannerSQSURL
      PromoteMode:
        default: PromoteMode
      QuarantineMode:
        default: QuarantineMode
Parameters:
  S3BucketToScan:
    AllowedPattern: ^[0-9a-z]+([0-9a-z-]*[0-9a-z])*$
    ConstraintDescription: S3 bucket name can include numbers, lowercase letters,
      and hyphens (-). It cannot start or end with a hyphen (-).
    Description: The S3 bucket to scan. Specify an the name of S3 Scan.
    Default: test
    Type: String
  S3QuarantineBucketDemoApp:
    AllowedPattern: ^[0-9a-z]+([0-9a-z-]*[0-9a-z])*$
    ConstraintDescription: S3 bucket name can include numbers, lowercase letters,
      and hyphens (-). It cannot start or end with a hyphen (-).
    Description: The S3 bucket to use for quarantine. Specify an the name of Quarantine S3.
    Default: test-quarantine
    Type: String

  ExternalID:
    Description: The External ID, You can get the External ID from the ScannerStack
      Parameters or by API https://cloudone.trendmicro.com/docs/file-storage-security/api-reference/#tag/External-ID
    Default: '123456789012'
    Type: String

  ScannerAWSAccount:
    Description: ''
    Default: '123456789012'
    Type: String

  ScannerSQSURL:
    Description: Scanner SQS URL, you can get the ScannerSQSURL from ScannerStack
      Outputs or by API https://cloudone.trendmicro.com/docs/file-storage-security/api-reference/tag/Stack#operation/describeStackByID
    Default: https://sqs.region.amazonaws.com/aws-account/ScannerFSS-ScannerQueue-
    Type: String

  AWSRegion:
    Description: AWS Region
    Default: us-east-1
    Type: String

  PromoteMode:
    Type: String
    AllowedValues:
    - move
    - copy
    Default: move
    Description: 'The method by which files were quarantined. (Options: move, copy)'
  QuarantineMode:
    Type: String
    AllowedValues:
    - move
    - copy
    Default: move
    Description: 'The method by which files were quarantined. (Options: move, copy)'
Conditions:
  PromoteEnabled:
    Fn::Not:
    - Fn::Equals:
      - Ref: S3BucketToScan
      - ''
  QuarantineEnabled:
    Fn::Not:
    - Fn::Equals:
      - Ref: S3QuarantineBucketDemoApp
      - ''
Resources:
  tmapi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
        - GET
        - POST
        - DELETE
        - OPTIONS
        AllowHeaders:
        - '*'
        AllowOrigins:
        - '*'
  CheckResultScan:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/resultScan.js
      Handler: resultScan.handler
      Runtime: nodejs12.x
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          UploadBucket:
            Ref: S3UploadBucket
          QuarantineBucket:
            Ref: S3QuarantineBucket
      Policies:
      - S3FullAccessPolicy:
          BucketName:
            Ref: S3UploadBucket
      - S3FullAccessPolicy:
          BucketName:
            Ref: S3QuarantineBucket
      Events:
        UploadAssetAPI:
          Type: HttpApi
          Properties:
            Path: /status
            Method: post
            ApiId:
              Ref: tmapi
  UploadRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/uploader.js
      Handler: uploader.handler
      Runtime: nodejs12.x
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          UploadBucket:
            Ref: S3UploadBucket
      Policies:
      - S3WritePolicy:
          BucketName:
            Ref: S3UploadBucket
      - LambdaInvokePolicy:
          FunctionName:
            Ref: CheckResultScan
      Events:
        UploadAssetAPI:
          Type: HttpApi
          Properties:
            Path: /uploads
            Method: get
            ApiId:
              Ref: tmapi
  S3UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - HEAD
          AllowedOrigins:
          - '*'
  S3QuarantineBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - HEAD
          AllowedOrigins:
          - '*'
  StorageStackFSS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: Templates/FSS-Storage-Stack.template
      Parameters:
        ExternalID:
          Ref: ExternalID
        ScannerAWSAccount:
          Ref: ScannerAWSAccount
        S3BucketToScan:
          Ref: S3UploadBucket
        ScannerSQSURL:
          Ref: ScannerSQSURL
  PromoteOrQuarantineLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handler.py
      Handler: handler.lambda_handler
      Runtime: python3.8
      MemorySize: 512
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          PROMOTEBUCKET:
            Ref: S3UploadBucket
          PROMOTEMODE:
            Ref: PromoteMode
          QUARANTINEBUCKET:
            Ref: S3QuarantineBucket
          QUARANTINEMODE:
            Ref: QuarantineMode
      Policies:
      - Statement:
          Effect: Allow
          Action:
          - s3:GetObject
          - s3:DeleteObject
          - s3:GetObjectTagging
          Resource:
          - Fn::Sub: arn:${AWS::Partition}:s3:::${S3UploadBucket}/*
      - Statement:
          Effect: Allow
          Action:
          - s3:PutObject
          - s3:PutObjectTagging
          Resource:
          - Fn::If:
            - PromoteEnabled
            - Fn::Sub: arn:${AWS::Partition}:s3:::${S3UploadBucket}/*
            - Ref: AWS::NoValue
          - Fn::If:
            - QuarantineEnabled
            - Fn::Sub: arn:${AWS::Partition}:s3:::${S3QuarantineBucketDemoApp}/*
            - Ref: AWS::NoValue
      Events:
        ScanResult:
          Type: SNS
          Properties:
            Topic:
              Fn::GetAtt:
              - StorageStackFSS
              - Outputs.ScanResultTopicARN
Outputs:
  APIendpoint:
    Description: HTTP API endpoint URL
    Value:
      Fn::Sub: https://${tmapi}.execute-api.${AWS::Region}.amazonaws.com
  S3UploadBucketName:
    Description: Upload Application for Demo C1 - FSS
    Value:
      Ref: S3UploadBucket
  StorageStackManagementRoleARN:
    Description: The ARN of the IAM role for File Storage Security backend services
      to manage the deployed resources.
    Value:
      Fn::GetAtt:
      - StorageStackFSS
      - Outputs.StorageStackManagementRoleARN
